# Introduction

Columnar data formats are a critical component of database management systems (DBMSs) optimized
for OLAP workloads today. Most such DBMSs provide some kind of compatibility with open-source 
formats like Parquet or ORC. These formats are a decade old. Recent works like Procella [@procella2019] 
go beyond OLAP to online serving that need real-time random access as well. These formats are optimized 
for tabular data. They are not sufficient for ML data characterized by much larger 
record sizes (e.g., vectors, images, videos, etc) and ML workloads including training and evaluation.
As a result, ML teams are often forced to create additional data siloes and managing multiple
copies of their data for different purposes, drastically increasing cost and complexity.

In addition, experimentation is critical to the continual improvement of ML systems. However, ML specific 
formats like tfrecords [<ref>] or webdataset [<ref>] require making a complete copy of the dataset
to add a new feature or perform some experiment-specifi transformation. These unnecessary copies are 
extremely costly in both developer time and cost of storage.

This paper presents Lance, a new columnar format as well as light-weight table format which solves
the challenges faced by existing formats across ML data types and workloads. Lance has the following
innovations:
1. Encoding that supports random access 100x [?] faster than parquet
2. Updated IO planning for large binary data
3. Zero-copy schema evolution and dataset versioning to support better ML experimentation
4. Indexing for fast and highly scalable vector search
5. Access patterns optimized ML training directly from modern object storage
