---
format: acm-pdf

# use keep-tex to cause quarto to generate a .tex file
# which you can eventually use with TAPS
keep-tex: true

bibliography: bibliography.bib

title: "Lance: A columnar format for AI data lakes"

author:
  - name: Will Jones
    affiliations:
      - name: LanceDB
        country: USA
    # orcid: 0000-0003-2402-304X
    email: willjones127@gmail.com
    # url: https://mm218.dev
  - name: Weston Pace
    affiliations:
      - name: LanceDB
        country: USA
  - name: Rob Meng
    affiliations:
      - name: LanceDB
        country: USA
  - name: Chang She
    affiliations:
      - name: LanceDB
        country: USA

  - name: Qian Zhu
    affiliations:
      - name: LanceDB
        country: USA
    # email:
  - name: Lei Xu
    affiliations:
      - name: LanceDB
        country: USA
    # email:

# acm-specific metadata
acm-metadata:
  # comment this out to make submission anonymous
  # anonymous: true

  # comment this out to build a draft version
  final: true

  # comment this out to specify detailed document options
  acmart-options: sigconf

  # acm preamble information
  copyright-year: 2024
  acm-year: 2024
  copyright: acmcopyright
  doi: XXXXXXX.XXXXXXX
  conference-acronym: "Conference acronym 'XX"
  conference-name: |
    Make sure to enter the correct
    conference title from your rights confirmation emai
  conference-date: June 03--05, 2018
  conference-location: Woodstock, NY
  price: "15.00"
  isbn: 978-1-4503-XXXX-X/18/06

  # if present, replaces the list of authors in the page header.
  shortauthors: Trovato et al.

  # The code below is generated by the tool at http://dl.acm.org/ccs.cfm.
  # Please copy and paste the code instead of the example below.
  ccs: |
    \begin{CCSXML}
    <ccs2012>
     <concept>
      <concept_id>10010520.10010553.10010562</concept_id>
      <concept_desc>Computer systems organization~Embedded systems</concept_desc>
      <concept_significance>500</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010575.10010755</concept_id>
      <concept_desc>Computer systems organization~Redundancy</concept_desc>
      <concept_significance>300</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010553.10010554</concept_id>
      <concept_desc>Computer systems organization~Robotics</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
     <concept>
      <concept_id>10003033.10003083.10003095</concept_id>
      <concept_desc>Networks~Network reliability</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
    </ccs2012>
    \end{CCSXML}

    \ccsdesc[500]{Computer systems organization~Embedded systems}
    \ccsdesc[300]{Computer systems organization~Redundancy}
    \ccsdesc{Computer systems organization~Robotics}
    \ccsdesc[100]{Networks~Network reliability}

  keywords:
    - datasets
    - neural networks
    - gaze detection
    - text tagging

  # if uncommented, this produces a teaser figure
  #
  # teaser:
  #   image: sampleteaser
  #   caption: figure caption
  #   description: teaser description

include-in-header:
  - table_workaround.tex

abstract: |
  A clear and well-documented \LaTeX\ document is presented as an
  article formatted for publication by ACM in a conference proceedings
  or journal publication. Based on the "acmart" document class, this
  article presents and explains many of the common variations, as well
  as many of the formatting elements an author may use in the
  preparation of the documentation of their work.

---

{{< include intro.qmd >}}

# Related work
{{< include related_work.qmd >}}

{{< include design.qmd >}}

{{< include experiments.qmd >}}

# Future work

Lance's primary optimization is sliceable data pages. For non-nullable plain-encoded data, this is straightfoward and performs well. However, future work is needed to determine how this optimization can be effectively applied to other encodings. For example, to support nullability, a null bitmap buffer could be added to a data page adjacent to the values buffer. To read single row for a plain-encoded array, the system will need to choose between making two small IOPs (one for the value, one for the null bit) and making a single larger IOP that covers both byte ranges. It's possible that more creative layouts and clever IO coalescing mechanisms can provide more optimal IO paths. Such work will likely need to balance minimizing total bytes read and total IOPS, possibly considering the characteristics of the storage system. For example, NVMe drives may have very low IOP overhead as well as a small minimum request size, while cloud object stores like AWS S3 have much higher per request overhead and higher minimum request size. Such work may build upon the encodings design described in @btrblocks.

Currently, Lance format lacks support for nullability and compression. Once the sliceable data pages optimizations are applied to a wider set of encodings, both of these will be possible.

As noted earlier, Lance does not support varying the number of rows per a page by column. This can be sub-optimal when some columns are small (such as a float32 column) while others are very large (such as a 1MB image column). A the default of 1024 rows, the page of floats will exceedingly small, even without compression. Meanwhile the image column would be near the upper limit of what an application would want to buffer in memory before flushing a row group to disk. Therefore, future work may redesign the Lance format to have a more flexible page layout.

Finally, this paper describes the file format, but not the Lance table format. The Lance table format adds features known to existing table formats, such as ACID guarantees over cloud object storage. Additionally, it supports secondary indices, which are made practical by Lance's fast random access. These secondary indices are written in immutable files similar to the data files of a table format. Future research may examine how to keep secondary indices up-to-date while balancing read latency and write amplification.

# Conclusion


# References {-}

