[package]
name = "row_group_io_parallelism"
version = "0.1.0"
edition = "2021"
default-run = "benchmark_io_parallelism"

[[bin]]
name = "benchmark_io_parallelism"
path = "src/main.rs"

[[bin]]
name = "run_query"
path = "src/run_query.rs"

[[bin]]
name = "benchmark_s3_io"
path = "src/s3_benchmark.rs"

[dependencies]
clap = { workspace = true }
parquet = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
arrow-buffer = { workspace = true }
lance = { workspace = true }
lance-encoding = { workspace = true }
lance-file = { workspace = true }
lance-io = { workspace = true }
lance-datafusion = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
object_store = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
datafusion = { workspace = true }
datafusion-execution = { workspace = true }
datafusion-physical-plan = { workspace = true }
datafusion-physical-expr = { workspace = true }
url = { workspace = true }
regex = "1.0"
utilities = { path = "../../utilities" }
aws-config = "1.0"
aws-sdk-s3 = "1.0"
pin-project = "1.0"